import { 
  Layers, 
  Volume2, 
  Smartphone, 
  Landmark, 
  Wrench, 
  Terminal, 
  Activity,
  Trophy,
  FileArchive,
  ScanFace,
  Navigation,
  QrCode,
  Medal,
  CalendarDays, // 시간표 및 일정 관리에 적합한 아이콘 추가
  Ghost,
  Briefcase,
  Croissant,
  Scale,
  Sprout
} from 'lucide-react';
import { ServiceItem } from './types';

export const SERVICES: ServiceItem[] = [
  {
    id: 'bank',
    title: '클래스뱅크',
    subtitle: '학급 안에서 직접 경험하는 금융·경제 실험실',
    description: '주식, 펀드, 적금은 물론 학생 간 송금, QR 결제까지 가능한 학급 금융경제 웹 서비스입니다. 교실 속에서 ‘경제가 돌아가는 경험’을 직접 만들어줍니다.',
    catchphrase: '👉 이론이 아닌, 경험으로 배우는 금융 수업',
    url: 'https://economy-rho.vercel.app/',
    icon: Landmark,
  },
  {
    id: 'game',
    title: '글겹게임',
    subtitle: '겹쳐진 글자 속에 숨겨진 정답을 찾아라',
    description: '겹쳐진 글자를 하나씩 펼쳐가며 교사가 직접 만든 문제를 해결하는 집중력과 사고력을 자극하는 학습형 게임입니다. 퀴즈, 어휘 학습, 추리 활동까지 수업에 바로 활용할 수 있습니다.',
    catchphrase: '👉 놀이처럼 시작해서 학습으로 끝나는 수업용 게임',
    url: 'https://ochre-nine.vercel.app/',
    icon: Layers,
  },
  {
    id: 'roles',
    title: '우리 반 1인 1역 매니저',
    subtitle: '우리 반 1인 1역을 스마트하게 배정하세요',
    description: '온라인으로 학생들에게 1인 1역 신청서를 받아보세요. 그리고 자동배정/수동배정 기능을 활용해 중복되지 않고 효율적으로 1인 1역을 배정해 보세요.',
    catchphrase: '👉 #1인 1역, #쉬운 배정, #간단한 출력, #온라인 수합, #학급운영',
    url: 'https://service-1-1-1083949389118.asia-east1.run.app',
    icon: Briefcase,
  },
  {
    id: 'diet',
    title: 'hwpx/pdf 용량 줄이기',
    subtitle: '무거운 hwpx와 pdf 파일의 용량을 쉽게 줄여보세요.',
    description: '높은 용량의 hwpx와 pdf 파일을 메시지로 보내거나 업무에 활용할 때 어려웠던 경험이 있으셨나요? 간단하게 파일을 업로드하고 다이어트 된 파일 용량을 확인해 보세요.',
    catchphrase: '👉 hwpx와 pdf 용량을 쉽게 줄여주는 서비스',
    url: 'https://hwpx-pdf-1083949389118.asia-east1.run.app',
    icon: FileArchive,
  },
  {
    id: 'faceblur',
    title: '쉽고 간단하게 얼수(얼굴수정)',
    subtitle: '학생 사진 얼굴 쉽게 가리기',
    description: 'AI가 사진 속 학생들의 얼굴을 자동으로 감지하여 블러(Blur) 처리합니다. 업로드한 이미지는 서버로 전송되지 않으며, 오직 사용자의 기기 내에서만 안전하게 처리됩니다.',
    catchphrase: '👉 AI 얼굴 인식을 통한 이미지 얼굴 가리기',
    url: 'https://faceblur-xi.vercel.app/',
    icon: ScanFace,
  },
  {
    id: 'gosite',
    title: 'GoSite(쉽게 연결해요)',
    subtitle: '한 번의 클릭으로 원하는 URL로 쉽게 이동!',
    description: '학생들 태블릿에 클릭 한 번으로 앱 아이콘을 추가합니다. 그 후부터는 학생들이 앱 아이콘만 클릭하면 교사가 원하는 사이트로 쉽게 이동시킬 수 있습니다. 번거로운 QR코드 인식은 그만! 클래스룸 같은 서비스가 어렵다면 사용해보세요.',
    catchphrase: '👉 학생들을 쉽고 간단하게 원하는 사이트로 이동하는 서비스',
    url: 'https://gosite-theta.vercel.app/',
    icon: Navigation,
  },
  {
    id: 'qwer',
    title: 'QWER(PC용 QR코드 스캐너)',
    subtitle: 'PC에서도 쉽고 간단하게 QR코드를 스캔하세요!',
    description: '가끔씩 PC로 날아오는 QR코드를 스캔하지 못해 스마트폰으로 번거롭게 스캔하신 경험이 있으신가요? 이제 PC에서도 쉽고 간단하게 QR코드를 스캔할 수 있습니다.',
    catchphrase: '👉 PC에서 쉽고 간단하게 QR코드 스캔 기능을 지원',
    url: 'https://qwerscan.vercel.app/',
    icon: QrCode,
  },
  {
    id: 'kidstimetable',
    title: '키즈 타임테이블 (Kids Time Table)',
    subtitle: '아이들의 스케쥴을 쉽고 간단하게 정리해 주세요',
    description: '센터, 학원, 문화센터 등 아이들의 다양한 일정들을 짜고 정리하는건 생각보다 힘든 일입니다. 키즈 타임테이블을 활용해서 쉽고 직관적으로 아이들의 일정을 정리해 보세요.',
    catchphrase: '👉 드래그 앤 드랍으로 쉽고 간단하게 일정 조율하기',
    url: 'https://kidstimetable.vercel.app/#/login',
    icon: CalendarDays,
  },
  {
    id: 'zombie',
    title: '지니어스 게임(좀비게임)',
    subtitle: "추억의 지니어스 게임 '좀비게임'을 더 쉽게!",
    description: "지니어스 게임 1 '좀비게임'을 지원하고 진행하기 위해 만들어진 서비스입니다. 선생님이 복잡하게 계산하실 필요 없이 이 서비스로 쉽고 간단하게 좀비게임을 해보세요.",
    catchphrase: '👉 #3학년 과학 감염병 단원, #학급놀이',
    url: 'https://zombiegame-cyan.vercel.app/',
    icon: Ghost,
  },
  {
    id: 'famine',
    title: '지니어스 게임(풍요와 기근)',
    subtitle: "추억의 지니어스 게임 '풍요와 기근'을 더 쉽게!",
    description: "지니어스 게임의 '풍요와 기근' 게임을 지원하고 진행하기 위해 만들어진 서비스입니다. 선생님이 복잡하게 계산하거나 운영하실 필요없이 이 서비스로 쉽고 간단하게 풍요와 기근 게임을 해보세요.",
    catchphrase: '👉 #6학년 수학 비와 비율, #지니어스 게임, #학급 놀이',
    url: 'https://breadg.vercel.app/',
    icon: Croissant,
  },
  {
    id: 'jury',
    title: '지니어스 게임(배심원)',
    subtitle: "지니어스한 학급 놀이 '배심원'을 해보세요!",
    description: "지니어스 게임의 '배심원' 게임을 지원하고 진행하기 위해 만들어진 서비스입니다. 선생님이 복잡하게 계산하거나 운영하실 필요없이 이 서비스로 쉽고 간단하게 배심원 게임을 해보세요.",
    catchphrase: '👉 #6학년 사회, #재판 배심원, #지니어스 게임, #학급 놀이',
    url: 'https://jurygame.vercel.app/',
    icon: Scale,
  },
  {
    id: 'beans_dilemma',
    title: '지니어스 게임(콩의 딜레마)',
    subtitle: "지니어스한 학급 놀이 '콩의 딜레마'를 해보세요!",
    description: "지니어스 게임의 '콩의 딜레마' 게임을 지원하고 진행하기 위해 만들어진 서비스입니다. 선생님이 복잡하게 계산하거나 운영하실 필요없이 이 서비스로 쉽고 간단하게 배심원 게임을 해보세요.",
    catchphrase: '👉 #5학년 도덕, #공익, #사익, #지니어스 게임, #학급 놀이',
    url: 'https://beandilemma.vercel.app/',
    icon: Sprout,
  },
  {
    id: 'kickball',
    title: '발야구 점수판',
    subtitle: '즐거운 발야구 손쉽게 카운팅하세요!',
    description: '발야구 하다보면 아웃, 스트라이크, 볼 카운트를 놓치는 경우가 많습니다. 선생님과 학생 모두 실시간으로 쉽고 간단하게 카운트와 점수를 확인/관리하는 도구입니다.',
    catchphrase: '👉 정확한 카운팅을 더 손쉽게 도와주는 서비스',
    url: 'https://kickball-swart.vercel.app/',
    icon: Trophy,
  },
  {
    id: 'facility',
    title: '시설 안전점검 및 보수요청',
    subtitle: '학교 시설 관리, 이제 종이와 전화 말고 웹으로',
    description: '학교 시설 보수 요청을 웹에서 간단하게 접수하고 진행 상황까지 한눈에 관리할 수 있는 서비스입니다. 현장의 번거로움을 줄이고 소통을 명확하게 만들어줍니다.',
    catchphrase: '👉 학교 행정을 가볍게 만드는 실무형 서비스',
    url: 'https://facilitymanagemet.vercel.app/',
    icon: Wrench,
  },
  {
    id: 'hacking',
    title: '가짜 해킹 사이트',
    subtitle: '영화 속 해킹 장면을 현실로',
    description: '졸업 영상 촬영을 위해 제작한 연출용 가짜 해킹 사이트입니다. 타이핑, 코드 흐름, 긴장감 있는 화면으로 마치 실제 해킹을 하는 듯한 분위기를 연출할 수 있습니다. world, danger 등의 키워드를 쳐보세요.',
    catchphrase: '👉 영상·행사 연출을 위한 몰입형 콘셉트 사이트',
    url: 'https://youware.app/project/uv0dxka2h4?enter_from=share&screen_status=2',
    icon: Terminal,
  },
  {
    id: 'sound',
    title: '빅 사운드 (Big Sound)',
    subtitle: '“소리가 더 컸으면…”이라는 순간을 해결해주는 도구',
    description: '태블릿이나 PC에서 음량이 부족할 때, 기본 한계를 넘어 더 크게 출력할 수 있도록 도와주는 서비스입니다. 체육 수업, 행사 진행, 영상 시청 시 유용하게 활용할 수 있습니다.',
    catchphrase: '👉 학교 현장에서 진짜 필요한 ‘볼륨 해결사’',
    url: 'https://bigsound-sigma.vercel.app/',
    icon: Volume2,
  },
  {
    id: 'pe',
    title: '권쌤과 클래스 리그',
    subtitle: '학급에서 진행하는 리그전을 스마트하게',
    description: '학급에서 공기놀이나 스포츠스태킹, 학급별 피구, 배드민턴 경기 등 다양한 리그전을 진행하게 됩니다. 리그전 경기 결과들을 체계적으로 정리하고 통계를 자동으로 생성해주는 서비스입니다. 교사가 커스텀 할 수 있습니다.',
    catchphrase: '👉 다양한 경기 결과를 정리해주는 서비스',
    url: 'https://classleague.vercel.app/',
    icon: Medal,
  },
  {
    id: 'pwa',
    title: 'PWA Builder',
    subtitle: '내 웹 서비스를 앱처럼 만들어주는 가장 쉬운 방법',
    description: '복잡한 개발 과정 없이 내가 만든 웹 서비스를 간단하게 PWA 앱으로 변환할 수 있습니다. 설치형 앱처럼 홈 화면에 추가하여 활용 가능합니다.',
    catchphrase: '👉 교사를 위한 가장 간단한 PWA 제작 도구',
    url: 'https://pwabuilder-liard.vercel.app/',
    icon: Smartphone,
  }
];